package com._LovelyBunny.Naturality.item;

import com._LovelyBunny.Naturality.Naturality;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class NaturalityCreativeTabs {
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TABS =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Naturality.MODID);

    public static final RegistryObject<CreativeModeTab> NATURALITY_TAB = CREATIVE_MODE_TABS.register("naturality_tab",
            () -> CreativeModeTab.builder().icon(() -> new ItemStack(NaturalityItems.MILKWEED.get()))
                    .title(Component.translatable("creativetab.naturality_tab"))
                    .displayItems((pParameters, pOutput) -> {
                        pOutput.accept(NaturalityItems.SANDY_SOIL.get());
//                        pOutput.accept(NaturalityItems.PEAT_MOSS.get());
                        pOutput.accept(NaturalityItems.MAPLE_LOG.get());
                        pOutput.accept(NaturalityItems.LINDEN_LOG.get());
                        pOutput.accept(NaturalityItems.DRACAENA_LOG.get());
                        pOutput.accept(NaturalityItems.BEECH_LOG.get());
                        pOutput.accept(NaturalityItems.LARCH_LOG.get());
                        pOutput.accept(NaturalityItems.JACARANDA_LOG.get());
                        pOutput.accept(NaturalityItems.MAPLE_WOOD.get());
                        pOutput.accept(NaturalityItems.LINDEN_WOOD.get());
                        pOutput.accept(NaturalityItems.DRACAENA_WOOD.get());
                        pOutput.accept(NaturalityItems.BEECH_WOOD.get());
                        pOutput.accept(NaturalityItems.LARCH_WOOD.get());
                        pOutput.accept(NaturalityItems.JACARANDA_WOOD.get());
                        pOutput.accept(NaturalityItems.STRIPPED_MAPLE_LOG.get());
                        pOutput.accept(NaturalityItems.STRIPPED_LINDEN_LOG.get());
                        pOutput.accept(NaturalityItems.STRIPPED_DRACAENA_LOG.get());
                        pOutput.accept(NaturalityItems.STRIPPED_BEECH_LOG.get());
                        pOutput.accept(NaturalityItems.STRIPPED_LARCH_LOG.get());
                        pOutput.accept(NaturalityItems.STRIPPED_JACARANDA_LOG.get());
                        pOutput.accept(NaturalityItems.STRIPPED_MAPLE_WOOD.get());
                        pOutput.accept(NaturalityItems.STRIPPED_LINDEN_WOOD.get());
                        pOutput.accept(NaturalityItems.STRIPPED_DRACAENA_WOOD.get());
                        pOutput.accept(NaturalityItems.STRIPPED_BEECH_WOOD.get());
                        pOutput.accept(NaturalityItems.STRIPPED_LARCH_WOOD.get());
                        pOutput.accept(NaturalityItems.STRIPPED_JACARANDA_WOOD.get());
                        pOutput.accept(NaturalityItems.MAPLE_PLANKS.get());
                        pOutput.accept(NaturalityItems.LINDEN_PLANKS.get());
                        pOutput.accept(NaturalityItems.DRACAENA_PLANKS.get());
                        pOutput.accept(NaturalityItems.BEECH_PLANKS.get());
                        pOutput.accept(NaturalityItems.LARCH_PLANKS.get());
                        pOutput.accept(NaturalityItems.JACARANDA_PLANKS.get());
                        pOutput.accept(NaturalityItems.MAPLE_STAIRS.get());
                        pOutput.accept(NaturalityItems.LINDEN_STAIRS.get());
                        pOutput.accept(NaturalityItems.DRACAENA_STAIRS.get());
                        pOutput.accept(NaturalityItems.BEECH_STAIRS.get());
                        pOutput.accept(NaturalityItems.LARCH_STAIRS.get());
                        pOutput.accept(NaturalityItems.JACARANDA_STAIRS.get());
                        pOutput.accept(NaturalityItems.MAPLE_SLAB.get());
                        pOutput.accept(NaturalityItems.LINDEN_SLAB.get());
                        pOutput.accept(NaturalityItems.DRACAENA_SLAB.get());
                        pOutput.accept(NaturalityItems.BEECH_SLAB.get());
                        pOutput.accept(NaturalityItems.LARCH_SLAB.get());
                        pOutput.accept(NaturalityItems.JACARANDA_SLAB.get());
                        pOutput.accept(NaturalityItems.MAPLE_FENCE.get());
                        pOutput.accept(NaturalityItems.LINDEN_FENCE.get());
                        pOutput.accept(NaturalityItems.BEECH_FENCE.get());
                        pOutput.accept(NaturalityItems.LARCH_FENCE.get());
                        pOutput.accept(NaturalityItems.JACARANDA_FENCE.get());
                        pOutput.accept(NaturalityItems.MAPLE_FENCE_GATE.get());
                        pOutput.accept(NaturalityItems.LINDEN_FENCE_GATE.get());
                        pOutput.accept(NaturalityItems.DRACAENA_FENCE_GATE.get());
                        pOutput.accept(NaturalityItems.BEECH_FENCE_GATE.get());
                        pOutput.accept(NaturalityItems.LARCH_FENCE_GATE.get());
                        pOutput.accept(NaturalityItems.JACARANDA_FENCE_GATE.get());
                        pOutput.accept(NaturalityItems.MAPLE_DOOR.get());
                        pOutput.accept(NaturalityItems.LINDEN_DOOR.get());
                        pOutput.accept(NaturalityItems.DRACAENA_DOOR.get());
                        pOutput.accept(NaturalityItems.BEECH_DOOR.get());
                        pOutput.accept(NaturalityItems.LARCH_DOOR.get());
                        pOutput.accept(NaturalityItems.JACARANDA_DOOR.get());
                        pOutput.accept(NaturalityItems.MAPLE_TRAPDOOR.get());
                        pOutput.accept(NaturalityItems.LINDEN_TRAPDOOR.get());
                        pOutput.accept(NaturalityItems.DRACAENA_TRAPDOOR.get());
                        pOutput.accept(NaturalityItems.BEECH_TRAPDOOR.get());
                        pOutput.accept(NaturalityItems.LARCH_TRAPDOOR.get());
                        pOutput.accept(NaturalityItems.JACARANDA_TRAPDOOR.get());
                        pOutput.accept(NaturalityItems.MAPLE_PRESSURE_PLATE.get());
                        pOutput.accept(NaturalityItems.LINDEN_PRESSURE_PLATE.get());
                        pOutput.accept(NaturalityItems.DRACAENA_PRESSURE_PLATE.get());
                        pOutput.accept(NaturalityItems.BEECH_PRESSURE_PLATE.get());
                        pOutput.accept(NaturalityItems.LARCH_PRESSURE_PLATE.get());
                        pOutput.accept(NaturalityItems.JACARANDA_PRESSURE_PLATE.get());
                        pOutput.accept(NaturalityItems.MAPLE_BUTTON.get());
                        pOutput.accept(NaturalityItems.LINDEN_BUTTON.get());
                        pOutput.accept(NaturalityItems.DRACAENA_BUTTON.get());
                        pOutput.accept(NaturalityItems.BEECH_BUTTON.get());
                        pOutput.accept(NaturalityItems.LARCH_BUTTON.get());
                        pOutput.accept(NaturalityItems.JACARANDA_BUTTON.get());
                        pOutput.accept(NaturalityItems.JACARANDA_CARPET.get());
                        pOutput.accept(NaturalityItems.MAPLE_LEAVES.get());
                        pOutput.accept(NaturalityItems.LINDEN_LEAVES.get());
                        pOutput.accept(NaturalityItems.DRACAENA_LEAVES.get());
                        pOutput.accept(NaturalityItems.BEECH_LEAVES.get());
                        pOutput.accept(NaturalityItems.LARCH_LEAVES.get());
                        pOutput.accept(NaturalityItems.JACARANDA_LEAVES.get());
                        pOutput.accept(NaturalityItems.JASMINE_LEAVES.get());
                        pOutput.accept(NaturalityItems.FLOWERING_JASMINE_LEAVES.get());
                        pOutput.accept(NaturalityItems.MAPLE_SAPLING.get());
                        pOutput.accept(NaturalityItems.LINDEN_SAPLING.get());
                        pOutput.accept(NaturalityItems.DRACAENA_SAPLING.get());
                        pOutput.accept(NaturalityItems.BEECH_SAPLING.get());
                        pOutput.accept(NaturalityItems.LARCH_SAPLING.get());
                        pOutput.accept(NaturalityItems.JACARANDA_SAPLING.get());
                        pOutput.accept(NaturalityItems.DENSE_GRASS.get());
                        pOutput.accept(NaturalityItems.VIOLET.get());
                        pOutput.accept(NaturalityItems.CLOVER.get());
                        pOutput.accept(NaturalityItems.FOUR_LEAF_CLOVER.get());
                        pOutput.accept(NaturalityItems.WISTERIA.get());
                        pOutput.accept(NaturalityItems.ALOE.get());
                        pOutput.accept(NaturalityItems.MILKWEED.get());
                        pOutput.accept(NaturalityItems.MAPLE_SIGN.get());
                        pOutput.accept(NaturalityItems.LINDEN_SIGN.get());
                        pOutput.accept(NaturalityItems.DRACAENA_SIGN.get());
                        pOutput.accept(NaturalityItems.BEECH_SIGN.get());
                        pOutput.accept(NaturalityItems.LARCH_SIGN.get());
                        pOutput.accept(NaturalityItems.JACARANDA_SIGN.get());
                        pOutput.accept(NaturalityItems.MAPLE_HANGING_SIGN.get());
                        pOutput.accept(NaturalityItems.LINDEN_HANGING_SIGN.get());
                        pOutput.accept(NaturalityItems.DRACAENA_HANGING_SIGN.get());
                        pOutput.accept(NaturalityItems.BEECH_HANGING_SIGN.get());
                        pOutput.accept(NaturalityItems.LARCH_HANGING_SIGN.get());
                        pOutput.accept(NaturalityItems.JACARANDA_HANGING_SIGN.get());
                        pOutput.accept(NaturalityItems.MAPLE_BOAT.get());
                        pOutput.accept(NaturalityItems.LINDEN_BOAT.get());
                        pOutput.accept(NaturalityItems.DRACAENA_BOAT.get());
                        pOutput.accept(NaturalityItems.BEECH_BOAT.get());
                        pOutput.accept(NaturalityItems.LARCH_BOAT.get());
                        pOutput.accept(NaturalityItems.JACARANDA_BOAT.get());
                        pOutput.accept(NaturalityItems.MAPLE_CHEST_BOAT.get());
                        pOutput.accept(NaturalityItems.LINDEN_CHEST_BOAT.get());
                        pOutput.accept(NaturalityItems.DRACAENA_CHEST_BOAT.get());
                        pOutput.accept(NaturalityItems.BEECH_CHEST_BOAT.get());
                        pOutput.accept(NaturalityItems.LARCH_CHEST_BOAT.get());
                        pOutput.accept(NaturalityItems.JACARANDA_CHEST_BOAT.get());
                        pOutput.accept(NaturalityItems.DRAGON_FRUIT.get());
                        pOutput.accept(NaturalityItems.BUTTERFLY_SPAWN_EGG.get());
                        pOutput.accept(NaturalityItems.MOTH_SPAWN_EGG.get());
                        pOutput.accept(NaturalityItems.BUTTERFLY_NET.get());
                        pOutput.accept(NaturalityItems.MONARCH_BUTTERFLY.get());
                        pOutput.accept(NaturalityItems.MORPHO_BUTTERFLY.get());
                        pOutput.accept(NaturalityItems.RED_ADMIRAL_BUTTERFLY.get());
                        pOutput.accept(NaturalityItems.LUNA_MOTH.get());
                        pOutput.accept(NaturalityItems.ROSY_MAPLE_MOTH.get());
                        pOutput.accept(NaturalityItems.DEATH_HEAD_HAWK_MOTH.get());
                    })
                    .build());
    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TABS.register(eventBus);
    }
}
