
    modLoader="javafml"
    loaderVersion="${loader_version_range}"
    logoFile="logo.png"
    license="All rights reserved"
[[mods]]
    modId="naturality"
    displayName="Naturality"
    description='''Adds many natural features to brighten up Minecraft world!'''
    version="${mod_version}"
    authors="_LovelyBunny"
[[dependencies.naturality]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.naturality]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.naturality]]
    modId="terrablender"
    mandatory=true
    versionRange="${terrablender_version_range}"
    ordering="NONE"
    side="BOTH"
